export interface SourceLanguageOption {
  readonly id: string;
  readonly displayName: string;
  readonly providerLabel: string;
}

const entries = [
  ["af", "Afrikaans"],
  ["sq", "Albanian"],
  ["am", "Amharic"],
  ["ar", "Arabic"],
  ["ay", "Aymara"],
  ["az", "Azerbaijani"],
  ["be", "Belarusian"],
  ["bn", "Bengali"],
  ["bho", "Bhojpuri"],
  ["bo", "Tibetan"],
  ["bs", "Bosnian"],
  ["bg", "Bulgarian"],
  ["ca", "Catalan"],
  ["ceb", "Cebuano"],
  ["cs", "Czech"],
  ["ku", "Kurdish"],
  ["zh", "Chinese"],
  ["da", "Danish"],
  ["de", "German"],
  ["et", "Estonian"],
  ["el", "Greek"],
  ["en", "English"],
  ["eo", "Esperanto"],
  ["ee", "Ewe"],
  ["fi", "Finnish"],
  ["fr", "French"],
  ["gaa", "Ga"],
  ["gl", "Galician"],
  ["gu", "Gujarati"],
  ["ht", "Haitian Creole"],
  ["ha", "Hausa"],
  ["he", "Hebrew"],
  ["hi", "Hindi"],
  ["hmn", "Hmong"],
  ["hr", "Croatian"],
  ["hu", "Hungarian"],
  ["hy", "Armenian"],
  ["ig", "Igbo"],
  ["id", "Indonesian"],
  ["it", "Italian"],
  ["jv", "Javanese"],
  ["ja", "Japanese"],
  ["kn", "Kannada"],
  ["ka", "Georgian"],
  ["kk", "Kazakh"],
  ["mn", "Mongolian"],
  ["km", "Khmer"],
  ["rw", "Kinyarwanda"],
  ["ky", "Kyrgyz"],
  ["ko", "Korean"],
  ["lo", "Lao"],
  ["ln", "Lingala"],
  ["lt", "Lithuanian"],
  ["lua", "Luba-Lulua"],
  ["lg", "Luganda"],
  ["lv", "Latvian"],
  ["ml", "Malayalam"],
  ["mr", "Marathi"],
  ["ms", "Malay"],
  ["mk", "Macedonian"],
  ["my", "Burmese"],
  ["nl", "Dutch"],
  ["no", "Norwegian"],
  ["ne", "Nepali"],
  ["nso", "Northern Sotho"],
  ["ny", "Chichewa"],
  ["pam", "Kapampangan"],
  ["pa", "Punjabi"],
  ["ps", "Pashto"],
  ["fa", "Persian"],
  ["mg", "Malagasy"],
  ["pl", "Polish"],
  ["pt", "Portuguese"],
  ["qu", "Quechua"],
  ["ro", "Romanian"],
  ["rn", "Rundi"],
  ["ru", "Russian"],
  ["sg", "Sango"],
  ["si", "Sinhala"],
  ["sk", "Slovak"],
  ["sl", "Slovenian"],
  ["sn", "Shona"],
  ["so", "Somali"],
  ["st", "Southern Sotho"],
  ["es", "Spanish"],
  ["sr", "Serbian"],
  ["ss", "Swati"],
  ["su", "Sundanese"],
  ["sv", "Swedish"],
  ["sw", "Swahili"],
  ["ta", "Tamil"],
  ["tt", "Tatar"],
  ["te", "Telugu"],
  ["tg", "Tajik"],
  ["fil", "Filipino"],
  ["th", "Thai"],
  ["ti", "Tigrinya"],
  ["tn", "Tswana"],
  ["ts", "Tsonga"],
  ["tk", "Turkmen"],
  ["tr", "Turkish"],
  ["ug", "Uyghur"],
  ["uk", "Ukrainian"],
  ["ur", "Urdu"],
  ["uz", "Uzbek"],
  ["ve", "Venda"],
  ["vi", "Vietnamese"],
  ["war", "Waray"],
  ["wo", "Wolof"],
  ["xh", "Xhosa"],
  ["yi", "Yiddish"],
  ["yo", "Yoruba"],
  ["zu", "Zulu"],
] as const;

const detectorIdentities: Readonly<Record<string, string>> = {
  afr: "af",
  als: "sq",
  amh: "am",
  arb: "ar",
  ayr: "ay",
  azj: "az",
  bel: "be",
  ben: "bn",
  bho: "bho",
  bod: "bo",
  bos: "bs",
  bul: "bg",
  cat: "ca",
  ceb: "ceb",
  ces: "cs",
  ckb: "ku",
  cmn: "zh",
  dan: "da",
  deu: "de",
  ekk: "et",
  ell: "el",
  eng: "en",
  epo: "eo",
  ewe: "ee",
  fin: "fi",
  fra: "fr",
  gaa: "gaa",
  glg: "gl",
  guj: "gu",
  hat: "ht",
  hau: "ha",
  heb: "he",
  hin: "hi",
  hms: "hmn",
  hnj: "hmn",
  hrv: "hr",
  hun: "hu",
  hye: "hy",
  ibo: "ig",
  ind: "id",
  ita: "it",
  jav: "jv",
  jpn: "ja",
  kan: "kn",
  kat: "ka",
  kaz: "kk",
  khk: "mn",
  khm: "km",
  kin: "rw",
  kir: "ky",
  kor: "ko",
  lao: "lo",
  lin: "ln",
  lit: "lt",
  lua: "lua",
  lug: "lg",
  lvs: "lv",
  mal: "ml",
  mar: "mr",
  min: "ms",
  mkd: "mk",
  mya: "my",
  nld: "nl",
  nno: "no",
  nob: "no",
  npi: "ne",
  nso: "nso",
  nya: "ny",
  pam: "pam",
  pan: "pa",
  pbu: "ps",
  pes: "fa",
  plt: "mg",
  pol: "pl",
  por: "pt",
  prs: "fa",
  qug: "qu",
  quy: "qu",
  quz: "qu",
  ron: "ro",
  run: "rn",
  rus: "ru",
  sag: "sg",
  sin: "si",
  slk: "sk",
  slv: "sl",
  sna: "sn",
  som: "so",
  sot: "st",
  spa: "es",
  srp: "sr",
  ssw: "ss",
  sun: "su",
  swe: "sv",
  swh: "sw",
  tam: "ta",
  tat: "tt",
  tel: "te",
  tgk: "tg",
  tgl: "fil",
  tha: "th",
  tir: "ti",
  tsn: "tn",
  tso: "ts",
  tuk: "tk",
  tur: "tr",
  uig: "ug",
  ukr: "uk",
  urd: "ur",
  uzn: "uz",
  ven: "ve",
  vie: "vi",
  war: "war",
  wol: "wo",
  xho: "xh",
  ydd: "yi",
  yor: "yo",
  zlm: "ms",
  zul: "zu",
};

export const SOURCE_LANGUAGES: readonly SourceLanguageOption[] = Object.freeze(
  entries.map(([id, displayName]) =>
    Object.freeze({ id, displayName, providerLabel: `${displayName} [${id}]` }),
  ),
);
const sourcesById = new Map(SOURCE_LANGUAGES.map((source) => [source.id, source]));

export function isSourceLanguageId(value: unknown): value is string {
  return typeof value === "string" && sourcesById.has(value);
}

export function getSourceLanguage(value: string): SourceLanguageOption | null {
  return sourcesById.get(value) ?? null;
}

export function getSourceLanguageForDetector(code: string): SourceLanguageOption | null {
  const id = Object.prototype.hasOwnProperty.call(detectorIdentities, code)
    ? detectorIdentities[code]
    : undefined;
  return id === undefined ? null : getSourceLanguage(id);
}

export function getSourceProviderLabel(value: string): string | null {
  return getSourceLanguage(value)?.providerLabel ?? null;
}
