export type LanguageEquivalence = "base" | "exact-script" | "exact-region";

export interface TargetLanguageOption {
  readonly id: string;
  readonly displayName: string;
  readonly providerLabel: string;
  readonly equivalence: LanguageEquivalence;
  readonly order: number;
}

const entries = [
  ["ab", "Abkhazian"],
  ["sq", "Albanian"],
  ["aa", "Afar"],
  ["ak", "Akan"],
  ["ar", "Arabic"],
  ["am", "Amharic"],
  ["as", "Assamese"],
  ["az", "Azerbaijani"],
  ["ee", "Ewe"],
  ["ay", "Aymara"],
  ["ga", "Irish"],
  ["et", "Estonian"],
  ["oc", "Occitan"],
  ["or", "Odia"],
  ["om", "Oromo"],
  ["os", "Ossetian"],
  ["ba", "Bashkir"],
  ["eu", "Basque"],
  ["be", "Belarusian"],
  ["pam", "Kapampangan"],
  ["bg", "Bulgarian"],
  ["nso", "Northern Sotho"],
  ["is", "Icelandic"],
  ["pl", "Polish"],
  ["bs", "Bosnian"],
  ["fa", "Persian"],
  ["bho", "Bhojpuri"],
  ["br", "Breton"],
  ["bo", "Tibetan"],
  ["tn", "Tswana"],
  ["ts", "Tsonga"],
  ["tt", "Tatar"],
  ["da", "Danish"],
  ["de", "German"],
  ["dv", "Dhivehi"],
  ["ru", "Russian"],
  ["fo", "Faroese"],
  ["fr", "French"],
  ["sa", "Sanskrit"],
  ["fil", "Filipino"],
  ["fj", "Fijian"],
  ["fi", "Finnish"],
  ["km", "Khmer"],
  ["kl", "Greenlandic"],
  ["ka", "Georgian"],
  ["gu", "Gujarati"],
  ["gn", "Guarani"],
  ["kk", "Kazakh"],
  ["ht", "Haitian Creole"],
  ["ko", "Korean"],
  ["ha", "Hausa"],
  ["nl", "Dutch"],
  ["ky", "Kyrgyz"],
  ["gl", "Galician"],
  ["ca", "Catalan"],
  ["gaa", "Ga"],
  ["cs", "Czech"],
  ["kn", "Kannada"],
  ["kha", "Khasi"],
  ["xh", "Xhosa"],
  ["co", "Corsican"],
  ["hr", "Croatian"],
  ["qu", "Quechua"],
  ["ku", "Kurdish"],
  ["la", "Latin"],
  ["lv", "Latvian"],
  ["lo", "Lao"],
  ["lt", "Lithuanian"],
  ["ln", "Lingala"],
  ["rn", "Rundi"],
  ["luo", "Luo"],
  ["lua", "Luba-Lulua"],
  ["lg", "Luganda"],
  ["lb", "Luxembourgish"],
  ["rw", "Kinyarwanda"],
  ["ro", "Romanian"],
  ["gv", "Manx"],
  ["mt", "Maltese"],
  ["mr", "Marathi"],
  ["mg", "Malagasy"],
  ["ml", "Malayalam"],
  ["ms", "Malay"],
  ["mk", "Macedonian"],
  ["mfe", "Mauritian Creole"],
  ["mi", "Maori"],
  ["mn", "Mongolian"],
  ["bn", "Bengali"],
  ["my", "Burmese"],
  ["hmn", "Hmong"],
  ["af", "Afrikaans"],
  ["st", "Southern Sotho"],
  ["ne", "Nepali"],
  ["new", "Newari"],
  ["no", "Norwegian"],
  ["pa", "Punjabi"],
  ["pt", "Portuguese"],
  ["pt-PT", "Portuguese (Portugal)", "exact-region"],
  ["ps", "Pashto"],
  ["ny", "Chichewa"],
  ["ja", "Japanese"],
  ["sv", "Swedish"],
  ["sm", "Samoan"],
  ["sr", "Serbian"],
  ["crs", "Seychellois Creole"],
  ["sg", "Sango"],
  ["si", "Sinhala"],
  ["sn", "Shona"],
  ["eo", "Esperanto"],
  ["sk", "Slovak"],
  ["sl", "Slovenian"],
  ["ss", "Swati"],
  ["sw", "Swahili"],
  ["gd", "Scottish Gaelic"],
  ["ceb", "Cebuano"],
  ["so", "Somali"],
  ["tg", "Tajik"],
  ["te", "Telugu"],
  ["ta", "Tamil"],
  ["th", "Thai"],
  ["to", "Tongan"],
  ["ti", "Tigrinya"],
  ["tum", "Tumbuka"],
  ["tr", "Turkish"],
  ["tk", "Turkmen"],
  ["war", "Waray"],
  ["cy", "Welsh"],
  ["ug", "Uyghur"],
  ["ve", "Venda"],
  ["wo", "Wolof"],
  ["ur", "Urdu"],
  ["uk", "Ukrainian"],
  ["uz", "Uzbek"],
  ["es", "Spanish"],
  ["fy", "Western Frisian"],
  ["he", "Hebrew"],
  ["el", "Greek"],
  ["haw", "Hawaiian"],
  ["sd", "Sindhi"],
  ["hu", "Hungarian"],
  ["su", "Sundanese"],
  ["hy", "Armenian"],
  ["ig", "Igbo"],
  ["it", "Italian"],
  ["yi", "Yiddish"],
  ["iu", "Inuktitut"],
  ["hi", "Hindi"],
  ["id", "Indonesian"],
  ["en", "English"],
  ["yo", "Yoruba"],
  ["vi", "Vietnamese"],
  ["jv", "Javanese"],
  ["zh-Hant", "Chinese (Traditional)", "exact-script"],
  ["zh-Hans", "Chinese (Simplified)", "exact-script"],
  ["dz", "Dzongkha"],
  ["zu", "Zulu"],
  ["kri", "Krio"],
] as const satisfies readonly (readonly [string, string, LanguageEquivalence?])[];

export const TARGET_LANGUAGES: readonly TargetLanguageOption[] = Object.freeze(
  [...entries]
    .sort((left, right) => (left[1] < right[1] ? -1 : left[1] > right[1] ? 1 : 0))
    .map(([id, displayName, equivalence], index) =>
      Object.freeze({
        id,
        displayName,
        providerLabel: `${displayName} [${id}]`,
        equivalence: equivalence ?? "base",
        order: index + 1,
      }),
    ),
);

const targetLanguagesById = new Map(TARGET_LANGUAGES.map((option) => [option.id, option]));
export function isTargetLanguageId(value: unknown): value is string {
  return typeof value === "string" && targetLanguagesById.has(value);
}

export function getTargetLanguage(value: string): TargetLanguageOption | null {
  return targetLanguagesById.get(value) ?? null;
}

export function getProviderLanguageLabel(value: string): string | null {
  if (value === "zh") return "Chinese [zh]";
  return getTargetLanguage(value)?.providerLabel ?? null;
}
